### PR TITLE
Add improvements for CMS integration

### PR DESCRIPTION
**Pull request by ashley-hebler**
Leaving this as a draft until we can confirm this is what we need for the CMS

### Changed
- `templates/__common__/config/tasks/graphics-meta.js:` Adds more keys to manifest.json output and simplified how it's logging those warning messages. Also makes it so graphics without a title won't output in the manifest file.
- `templates/graphic/app/index.html`,  `templates/graphic/app/static.html`, `templates/graphic/app/templates/base.html` - Adds caption because we're now using description as the field for screenreaders/accessibility
-  `templates/__common__/config/utils.js` - Adds a helper for console logging with colors
- `templates/graphic/graphics-meta.md` - Documents the new caption field and rules.
- `templates/graphic/project.config.js` - Updates the default tag to be more of a catch all. This is to account for the event that someone doesn't update those tags in the project config, which seemed to be the case for the first handful we've done. @mandicai, does that sound like the right solve to you? Should they default as blank instead?

## Test steps
1. Check out `graphics-meta-fixes` and run `your/path/to/data-visuals-create/bin/data-visuals-create graphic my-test-graphic`
2. In that new project, add some sample HTML to the index.html. Feel free to use something from an old project or just this [test HTML](https://gist.github.com/ashley-hebler/44632a2c7eef5064b4d2b602dd100b97) I've been using.
3. Run `npm run serve` to preview the graphic.
4. Run `npm run build`
5. Confirm you see `caption:` appearing in the manifest.json output now.
6. Confirm the other new keys are there: `lastBuildTime`, `bucket`, `folder`, `graphicURL`
7. Leave either `graphicTitle` or `data-title` blank in your apps .html file. Run `npm run build`  again and confirm the graphic does not show up in the manifest now.

### CODE REVIEW

**Comment by mandicai** [comment]
@ashley-hebler Yeah that makes sense to have a catchall for the default tags. I've added a comment above the tags property in the config that links to our guten tags, so someone can easily find them.

**Comment by ashley-hebler** [comment]
> I've added a comment above the tags property in the config that links to our guten tags in #80, so someone can easily find them.

Saw that! Good call

**Comment by mandicai** [comment]
This looks good to me! I made a test graphic and confirmed all the properties made it to the manifest, and  the graphic does not show up if there's no title.

Curious if this is would work in tandem with our parserOptions in the config file? Or is that not being used anymore?

**Comment by ashley-hebler** [comment]
Cool and ff502d0 is a good add btw. Yeah that was kinda the idea with that parserOptions key - that it'd be used for specific settings. The no title == no manifest output came out of seeing many title-less graphics in the ones we've done so far. There's some balance between stuff just working without thinking about it and relying on specific steps with each graphic. The other way to prevent any parsing would be to remove the `data-graphic` attribute in`<div class="app" data-graphic>` in the HTML file. A few ways to do the same thing seems more user-friendly I guess. Or maybe it's more confusing! Either way I'll mark this as ready for review and we can merge/release at your convenience @mandicai. Thanks for taking a look and testing this!

**Pull request merged**
